<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE etiqueta [
   <!ELEMENT etiqueta (nombre,calle,ciudad,pais,codigo)>
   <!ELEMENT nombre (#PCDATA)>
   <!ELEMENT calle (#PCDATA)>
   <!ELEMENT ciudad (#PCDATA)>
   <!ELEMENT pais (#PCDATA)>
   <!ELEMENT codigo (#PCDATA)>
]>
<etiqueta>
    <nombre>Roberto García</nombre>
    <calle>c/ Mayor, 27</calle>
    <ciudad>Coslada</ciudad>
    <pais>España</pais>
    <codigo>39343</codigo>
</etiqueta>
















<sudoku>
        <dato celda="A2" valor="1"/>
        <dato celda="B2" valor="2"/>
        <dato celda="A3" valor="3"/>
        <dato celda="D4" valor="1"/>
    </sudoku>