<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE matricula [
   <!ELEMENT matricula (personal,pago)>
   <!ELEMENT personal (dni,nombre,titulacion,curso_academico,domicilios)>
   <!ELEMENT dni (#PCDATA)>
   <!ELEMENT nombre (#PCDATA)>
   <!ELEMENT titulacion (#PCDATA)>
   <!ELEMENT curso_academico (#PCDATA)>
   <!ELEMENT domicilios (domicilio+)>
   <!ELEMENT domicilio (direccion,tipo)>  
   <!ELEMENT direccion (#PCDATA)>
   <!ELEMENT tipo (#PCDATA)>
   <!ELEMENT pago (tipo_matricula)>
   <!ELEMENT tipo_matricula (#PCDATA)>
   <!ATTLIST tipo domicilio CDATA "familiar">
   <!ATTLIST tipo domicilio CDATA "habitual">
]>

<matricula>
    <personal>
        <dni>99223366M</dni>
        <nombre>Juan Pardo Martín</nombre>
        <titulacion>Ingeniería Informática</titulacion>
        <curso_academico>1997/1998</curso_academico>
        <domicilios>
           <domicilio tipo="familiar"><direccion>C/ Principal nº1</direccion></domicilio>
           <domicilio tipo="habitual"><direccion>C/ Secundaria nº2</direccion></domicilio>
        </domicilios>
    </personal>
    <pago>
        <tipo_matricula>Matrícula Ordinaria</tipo_matricula>
    </pago>
</matricula>